name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout repo and submodules
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: make 
      run: make test
